# In the shared config repository for hyre
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/meraihan/config-server.git
          clone-on-start: true
      label: main

  datasource:
    url: jdbc:postgresql://localhost:5432/hyre
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
